### Online Retail Analytics
#### Data Understanding and Cleaning
This notebook focuses on understanding the raw dataset,
identifying data quality issues, cleaning the data,
and creating a cleaned dataset for analysis.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_2009=pd.read_excel("online_retail_II.xlsx",sheet_name="Year 2009-2010")
df_2010=pd.read_excel("online_retail_II.xlsx",sheet_name="Year 2010-2011")

In [6]:
df_2009.shape

(525461, 8)

In [7]:
df_2010.shape

(541910, 8)

#### Data Understanding

In [11]:
df_2009.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [12]:
df_2010.columns

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')

In [14]:
df_2009.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom
6,489434,21871,SAVE THE PLANET MUG,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
7,489434,21523,FANCY FONT HOME SWEET HOME DOORMAT,10,2009-12-01 07:45:00,5.95,13085.0,United Kingdom
8,489435,22350,CAT BOWL,12,2009-12-01 07:46:00,2.55,13085.0,United Kingdom
9,489435,22349,"DOG BOWL , CHASING BALL DESIGN",12,2009-12-01 07:46:00,3.75,13085.0,United Kingdom

In [15]:
df_2010.head(10)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom

In [16]:
df_2009.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [17]:
df_2010.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[us]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [76]:
df=pd.concat([df_2009,df_2010],ignore_index=True)

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [35]:
df.shape

(1067371, 8)

In [36]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [38]:
df.describe()

           Quantity                 InvoiceDate         Price    Customer ID
count  1.067371e+06                     1067371  1.067371e+06  824364.000000
mean   9.938898e+00  2011-01-02 21:13:55.394029  4.649388e+00   15324.638504
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04   12346.000000
25%    1.000000e+00         2010-07-09 09:46:00  1.250000e+00   13975.000000
50%    3.000000e+00         2010-12-07 15:28:00  2.100000e+00   15255.000000
75%    1.000000e+01         2011-07-22 10:23:00  4.150000e+00   16797.000000
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04   18287.000000
std    1.727058e+02                         NaN  1.235531e+02    1697.464450

#### Data Quality Assessment

In [65]:
df.duplicated().sum()

np.int64(34335)

In [41]:
(df["Quantity"]<0).sum()

np.int64(22950)

In [47]:
(df["Price"]<0).sum()

np.int64(5)

In [45]:
df["Customer ID"].isnull().sum()

np.int64(243007)

In [66]:
#These are the cancelled transactions
df["Invoice"].astype(str).str.startswith("C").sum()

np.int64(19494)

In [63]:
#This gives us the rows where quantity is negative but the invoice doesn't start with "C".
df[(df["Quantity"]<0) & (~df["Invoice"].astype(str).str.startswith("C"))]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0,NaN,United Kingdom
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1060794,581210,23395,check,-26,2011-12-07 18:36:00,0.0,NaN,United Kingdom
1060796,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,NaN,United Kingdom
1060797,581213,22576,check,-30,2011-12-07 18:38:00,0.0,NaN,United Kingdom
1062371,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,NaN,United Kingdom
1064386,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

#### Observation
Negative quantities are not always associated with cancelled invoices.
Approximately **3,457 records** contain negative quantities without a corresponding invoice starting with **'C'**.
A closer inspection shows that these records commonly have:
- Price equal to **0**
- Missing **CustomerID**
- Inventory adjustment descriptions such as **"missing"**, **"smashed"**, **"check"**, etc.
These records appear to represent internal inventory adjustments rather than customer sales transactions.

#### Cleaning the data

In [78]:
# Removing exact duplicate rows
df= df.drop_duplicates()

In [79]:
# Verifying
df.duplicated().sum()

np.int64(0)

In [80]:
# Removing Cancelled orders (Invoices starting with C)
df=df[~df["Invoice"].astype(str).str.startswith("C")]

In [84]:
# Verifying
df["Invoice"].astype(str).str.startswith("C").sum()

np.int64(0)

In [85]:
# Removing Negative Quantities
df=df[df["Quantity"]>0]

In [86]:
# Verifying
(df["Quantity"]<0).sum()

np.int64(0)

In [90]:
# Removing Negative Price
df=df[df["Price"]>0]

In [91]:
# Verifying
(df["Price"]<0).sum()

np.int64(0)

In [88]:
# Removing records with no description
df=df.dropna(subset=["Description"])

In [89]:
# Verifying
df["Description"].isnull().sum()

np.int64(0)

Customer ID will be retained for now missing Customer IDs will be handled separately during customer analysis

#### Feature Engineering

In [92]:
# Creating Revenue Column
df["Revenue"]=df["Quantity"]*df["Price"]

In [93]:
# Converting InvoiceDate to datetime
df["InvoiceDate"]=pd.to_datetime(df["InvoiceDate"])

In [96]:
# Extracting Year
df["Year"]=df["InvoiceDate"].dt.year

In [97]:
# Extracting Month Number
df["Month"]=df["InvoiceDate"].dt.month

In [98]:
# Extracting Month Name
df["Month_Name"]=df["InvoiceDate"].dt.month_name()

#### Final Quality Check

In [99]:
df.info()

<class 'pandas.DataFrame'>
Index: 1007913 entries, 0 to 1067370
Data columns (total 12 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1007913 non-null  object
 1   StockCode    1007913 non-null  object
 2   Description  1007913 non-null  object
 3   Quantity     1007913 non-null  int64
 4   InvoiceDate  1007913 non-null  datetime64[us]
 5   Price        1007913 non-null  float64
 6   Customer ID  779425 non-null   float64
 7   Country      1007913 non-null  str
 8   Revenue      1007913 non-null  float64
 9   Month        1007913 non-null  int32
 10  Month_Name   1007913 non-null  str
 11  Year         1007913 non-null  int32
dtypes: datetime64[us](1), float64(3), int32(2), int64(1), object(3), str(2)
memory usage: 92.3+ MB

In [100]:
df.isnull().sum()

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    228488
Country             0
Revenue             0
Month               0
Month_Name          0
Year                0
dtype: int64

In [101]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID,Revenue,Month,Year
count,1.007913e+06,1007913,1.007913e+06,779425.000000,1.007913e+06,1.007913e+06,1.007913e+06
mean,1.111718e+01,2011-01-04 10:34:18.759595,4.074252e+00,15320.360461,2.031550e+01,7.403545e+00,2.010437e+03
min,1.000000e+00,2009-12-01 07:45:00,1.000000e-03,12346.000000,1.000000e-03,1.000000e+00,2.009000e+03
25%,1.000000e+00,2010-07-06 11:21:00,1.250000e+00,13971.000000,4.130000e+00,4.000000e+00,2.010000e+03
50%,4.000000e+00,2010-12-09 15:29:00,2.100000e+00,15247.000000,1.008000e+01,8.000000e+00,2.010000e+03
75%,1.200000e+01,2011-07-28 12:29:00,4.130000e+00,16794.000000,1.770000e+01,1.100000e+01,2.011000e+03
max,8.099500e+04,2011-12-09 12:50:00,2.511109e+04,18287.000000,1.684696e+05,1.200000e+01,2.011000e+03
std,1.284700e+02,NaN,5.043045e+01,1695.692775,2.057158e+02,3.499747e+00,5.764132e-01

#### Saving the Clean Dataset

In [102]:
df.to_csv("data/cleaned/online_retail_cleaned.csv",index=False)

#### Cleaning Summary

The dataset was cleaned and prepared for exploratory data analysis by performing the following steps:

- Removed duplicate records.
- Removed cancelled transactions.
- Removed records with negative quantities.
- Removed records with invalid (zero or negative) prices.
- Removed records with missing product descriptions.
- Created new features, including **Revenue**, **Month**, **Month_Name**, and **Year**.
- Exported the cleaned dataset for use in the Exploratory Data Analysis (EDA) notebook.

The cleaned dataset is now ready for further analysis and visualization.